#!/usr/bin/env bash
# docker_xdebug - attach to a running container and debug a file or test
#
# This script was built to be integrated into phpstorm. When done, you will be able to start/debug unit tests, codeception tests with a click from within phpstorm.
function usage
{
    echo "usage: bash docker_xdebug [options]
Options:
    --container=         The docker container that should be use for execution. [required when -p|--project-name is absent]
    --codeception        Debug codeception tests.
    --docker-gateway=    The ip of the docker network gateway. This allows xdebug to connect to your host. [default: ${LOCAL_DOCKER_DNS}]
    --file=              File to debug relative to project root.
    --idekey=            Your xdebug idekey. [default: xdebug]
    --method=            Method to debug. Works only in combination with -f|--file.
    --php                Debug php files. [default]
    --phpunit            Debug php unit tests.
    --project-name=      The name of the project directory. This is used to automatically determine the docker container. [required when -c|--container is absent]
    --server=            PHPStorm configuration (Languages & Framework -> PHP -> Servers) [default: local]

    --help               Print the this help page.
    "
}

docker_net_gateway=${LOCAL_DOCKER_DNS}
idekey=xdebug
project=
serverName=local

while [ "$1" != "" ]; do
    key=$(echo $1 | cut -d "=" -f1)
    value=$(echo $1 | awk -F\= '{print $NF}')

    case $key in
        --server )          serverName=$value
                            ;;
        --container )       docker-container=$value
                            ;;
        --file )            file=$value
                            ;;
        --method )          if [ ! -z $value ]; then method=:$value; fi
                            ;;
        --idekey )          idekey=$value
                            ;;
        --docker-gateway )  docker_net_gateway=$value
                            ;;
        --project-name )    project=$value
                            ;;
        --codeception )     executable="vendor/bin/codecept run"
                            ;;
        --phpunit )         executable=vendor/bin/phpunit
                            ;;
        --php )             executable=/usr/bin/php
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

# determine the docker container running php (get the last chunk of a string that is separated by a dot)
if [ ! -z "$project" ]; then
    docker_container=`echo $(echo "$project" | awk -F. '{print $NF}')-php`
fi

docker exec "$docker_container" \
    bash -c "XDEBUG_CONFIG='idekey=$idekey' \
             PHP_IDE_CONFIG='serverName=$serverName' \
             php \
                -dxdebug.remote_autostart=1 \
                -dxdebug.remote_host=${docker_net_gateway} \
                ${executable} $file$method"